services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: shorteddy-db
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shorteddy-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend-gateway
    volumes:
      - ./src/krakend/krakend.json:/etc/krakend/krakend.json:ro
    ports:
      - "8081:8080"
    networks:
      - app-network

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npm run migration:run"]
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: shorteddy-db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
